### PR TITLE
Awana parent manual update to 2018-19, but without confirmed schedule

### PR DESCRIPTION
**Pull request by agathay**
Awana schedule has not been confirmed yet by Henry, so only update parent manual for now per Jennifer request.

### CODE REVIEW

**Comment by agathay** [comment]
AWANA parent manual update to 2018-19, but without schedule which has not yet been confirmed

**Review by lusha123 — APPROVED** [review]
Thank you.

**Review by lusha123 — APPROVED** [review]
Approved

**Comment by lusha123** [comment]
approved

**Pull request closed without merging**
